import type { RubricDefinition } from "./types";

/** SWE Test 1: harden and ship (docs/07, docs/09 §6). F-codes are INTERNAL: never shown to candidates. */

export const FAULT_KEY = [
  { id: "F01", fault: "customers table has RLS disabled", category: "Security", weight: 2, detection: "Harness RLS probe + advisor", harness: ["R3", "U3"] },
  { id: "F02", fault: "interactions has RLS with policy using (true) for authenticated: any agent sees every agent's interactions", category: "Security", weight: 2, detection: "Cross-tenant probe", harness: ["U4"] },
  { id: "F03", fault: "Default anon grants on lines plus a permissive select policy for anon added \"for the demo\"", category: "Security", weight: 2, detection: "Unauthenticated REST probe", harness: ["U3"] },
  { id: "F04", fault: "Service-role key in NEXT_PUBLIC_SUPABASE_SERVICE_KEY, used in one client component", category: "Security", weight: 2, detection: "Bundle scan", harness: ["R2", "U2"] },
  { id: "F05", fault: "/api/summary (OpenRouter) has no auth, no rate limit and no max tokens", category: "Cost/abuse", weight: 2, detection: "Burst probe (expect 401/429)", harness: ["U5"] },
  { id: "F06", fault: "User text interpolated straight into the AI prompt with other customers' data (prompt-injection / data-leak path)", category: "Security", weight: 2, detection: "Human review + injection probe", harness: [] },
  { id: "F07", fault: "No migrations: schema created by hand, schema.sql out of date", category: "Ops", weight: 1, detection: "supabase/migrations/ + db reset", harness: ["R3"] },
  { id: "F08", fault: "Import deletes all rows then inserts: customer IDs change monthly and interaction history is orphaned", category: "Data", weight: 1, detection: "Month-2 harness", harness: ["M1", "M2", "M6"] },
  { id: "F09", fault: "Phone numbers stored as numbers (leading zero lost)", category: "Data", weight: 1, detection: "Data check after import (D-a)", harness: ["D-a"] },
  { id: "F10", fault: "\"Call back\" saves without a callback date (UI-only validation)", category: "Correctness", weight: 1, detection: "API probe", harness: ["U6"] },
  { id: "F11", fault: "Contract status read from the stale export column instead of derived from the end date", category: "Correctness", weight: 1, detection: "Data check (D-b)", harness: ["D-b"] },
  { id: "F12", fault: "Opt-out list not applied to messaging", category: "Compliance", weight: 1, detection: "Data check: an opted-out customer can be messaged", harness: ["U7"] },
  { id: "F13", fault: ".env.local committed early and later deleted: the secret is still in history", category: "Security", weight: 2, detection: "gitleaks", harness: ["R1"] },
  { id: "F14", fault: "No error handling on the import: a bad row crashes the run silently, leaving a partial import", category: "Ops", weight: 1, detection: "Month-2 harness", harness: ["M5", "M7"] },
] as const;

export const HARNESS_CHECKS: Record<string, string> = {
  R1: "gitleaks over full history: the F13 secret is gone from history or the README documents the key rotation (ideal: both)",
  R2: "No service_role / SERVICE / sb_secret_ in NEXT_PUBLIC_* or 'use client' files",
  R3: "supabase/migrations/ exists and applies cleanly; every table has RLS",
  R4: "npm ci && lint && tsc --noEmit && build exit 0",
  R5: "Tests exist and pass: at least one covers the import and one covers RD-07",
  R6: ".github/workflows exists and the last run on the SHA is green",
  R7: ".env* gitignored and .env.example exists",
  U1: "GET /api/health returns 200 and touches the DB",
  U2: "Bundle scan: no service-role JWT, no secret key in HTML/JS",
  U3: "Unauthenticated REST probe on customers, lines, interactions: empty or rejected",
  U4: "Cross-tenant: agent A cannot read agent B's interactions/allocations",
  U5: "AI route burst: 401 unauthenticated; 429 within the burst (or a documented per-user cap) authenticated",
  U6: "RD-07: POST call_back without a date via the API is rejected (4xx)",
  U7: "RD-11: queueing a message to an opted-out customer (matched by name) is blocked",
  U8: "Security headers grade (informational)",
  M1: "Customer count increases only by the true number of new customers",
  M2: "Sentinel customers' interaction history intact (same IDs)",
  M3: "Changed lines updated, not duplicated",
  M4: "Removed lines marked inactive/ported, not deleted",
  M5: "Quarantine report lists the ambiguous and invalid rows, with reasons",
  M6: "Re-uploading the same month-2 file changes nothing",
  M7: "Drift file (renamed + added column) fails loudly naming the column, with no partial data",
  "D-a": "Phones stored as E.164 text; landlines distinguished from mobiles",
  "D-b": "Contract status derived from the end date",
  "D-c": "Epoch dates null or quarantined",
};

export const SWE_TEST1: RubricDefinition = {
  key: "swe_test1",
  version: 1,
  title: "SWE Test 1: harden and ship",
  criteria: [
    {
      key: "s1_fault_discovery",
      title: "S1 Fault discovery and fix",
      weight: 30,
      method: "computed",
      computation: "fault_points",
      prompt: "answer-key-grader",
      evidence_required: true,
      sources: ["readme"],
      reference_keys: ["fault_key"],
      description:
        "F01–F14 found and properly fixed, weighted (security F01–F06 and F13 weight 2, the rest 1; max 21), mapped from the README's found/fixed list: found = found and properly fixed with a correct explanation; partial = found but not fixed, fix incomplete, or explanation wrong. Harness results confirm or downgrade fixes when present. Includes S7 security posture (U2–U5, R1–R2). Points map to the anchors linearly in between.",
      anchors: { "1": "< 6 points of 21", "3": "10–14 points", "5": "≥ 18 points, with correct explanations" },
    },
    {
      key: "s2_import",
      title: "S2 Monthly import",
      weight: 25,
      method: "computed",
      computation: "harness_import",
      prompt: "grader-criterion",
      evidence_required: true,
      sources: ["readme", "harness"],
      reference_keys: ["harness_checks", "month2_expectations"],
      description:
        "Scored from the month-2 harness (M1–M7) when it has run. Without harness results the judge reads the README's account of the import and the score needs a human (review reason: harness not run).",
      anchors: {
        "1": "Fails M1 or M6: re-running duplicates customers or changes data; history does not survive a month",
        "3": "Passes M1–M3 and M6: idempotent, customers not duplicated, changed lines updated in place",
        "5": "Passes all M1–M7 with a clear quarantine report: removed lines kept as ported/inactive, and a schema drift fails loudly with no partial data",
      },
    },
    {
      key: "s3_stories",
      title: "S3 Stories RD-07 and RD-11",
      weight: 10,
      method: "computed",
      computation: "harness_stories",
      prompt: "grader-criterion",
      evidence_required: true,
      sources: ["readme", "harness"],
      reference_keys: ["harness_checks", "stories"],
      description: "RD-07 (mandatory callback date) and RD-11 (opt-out enforcement) against their ACs: harness U6/U7 plus tests (R5); README-based judgement when the harness has not run.",
      anchors: {
        "1": "Neither story enforced server-side (UI-only checks, or not implemented)",
        "3": "One story enforced at the DB/API level",
        "5": "Both enforced at the DB/API level, with tests",
      },
    },
    {
      key: "s4_deploy_ops",
      title: "S4 Deployment and ops",
      weight: 15,
      method: "computed",
      computation: "harness_deploy",
      prompt: "grader-criterion",
      evidence_required: true,
      sources: ["readme", "harness"],
      reference_keys: ["harness_checks"],
      description: "R4–R7, U1, CI, monitoring and resourceful hosting; README-based judgement when the harness has not run.",
      anchors: {
        "1": "Not deployed, or broken",
        "3": "Deployed; some ops basics (builds, env handled, partial CI or tests)",
        "5": "Deployed; CI green; health check; error monitoring; rollback note",
      },
    },
    {
      key: "s9_communication",
      title: "S9 Communication",
      weight: 20,
      method: "llm",
      prompt: "grader-criterion",
      evidence_required: true,
      sources: ["readme", "release_notes", "adr", "loom"],
      reference_keys: ["communication_expectations"],
      description: "README found/fixed and didn't-do lists, ADR-001, the release note written for Lerato, and the Loom.",
      anchors: {
        "1": "Unclear, or missing",
        "3": "Clear but technical",
        "5": "The release note is understandable to an exec; the ADR shows real trade-offs; the \"didn't do\" list shows prioritisation",
      },
    },
  ],
  reference: {
    fault_key: { total: 21, note: "Security faults F01–F06 and F13 weigh 2; the rest 1.", items: FAULT_KEY },
    harness_checks: HARNESS_CHECKS,
    month2_expectations:
      "base_month2.xlsx: 4% of lines changed, 2% new (15 for existing customers), 1.5% removed (ported), 30 duplicate rows, 20 new phone-format spellings of existing numbers, 10 ambiguous dates. base_month2_drift.xlsx renames Contract End Date → Contract_End and adds Sales_Rep. Exact counts: datasets/<version>/bundle_c/internal/expected_month2.json.",
    stories: {
      "RD-07": "Mandatory callback date: a Call back outcome cannot be saved without a date, enforced by the DB or API, not only the UI.",
      "RD-11": "Opt-out enforcement: the legal list is matched to customers (by company name, with variants) and no message can be queued to an opted-out customer.",
    },
    communication_expectations: [
      "README: architecture, how to run, decisions, what was found and fixed, and what was deliberately not done",
      "RELEASE_NOTES.md: half a page for Lerato (client GM): what changed for her team, in business terms",
      "docs/ADR-001.md: one real choice, the options, and why",
      "Loom: the three most important changes",
    ],
  },
};
