import { rands } from "@/lib/format";
import type { PlanClaim, ProbeDef } from "./types";

/**
 * Fixed interview wording (docs/05 Part A). The interviewer is a deterministic script: the
 * same core questions, standard probes and anchored scoring are what give a structured
 * interview its validity, so no question text is generated by an LLM.
 */

export const TOTAL_QUESTIONS = 6;
export const MAX_PROBES_PER_CLAIM = 2;
export const CLAIMS_PER_INTERVIEW = 3;

export const WARMUP_QUESTION = "In two or three sentences, what kind of work do you do best?";

/** Standard probes, in doc order (the fallback order when JEV is unavailable). */
export const PROBES: readonly ProbeDef[] = [
  { key: "hardest_decision", text: "What was the hardest technical or analytical decision in that work, and what did you reject?" },
  { key: "what_broke", text: "What broke, and how did you find out?" },
  { key: "differently", text: "What would you do differently?" },
  { key: "ai_tools", text: "Which parts did AI tools do, and how did you check them?" },
];

export const SITUATIONAL: Readonly<Record<string, string>> = {
  "business-analyst":
    "A client's ops head says 'just put all our leads on WhatsApp.' You have a spreadsheet of 5,000 customer lines with no phone numbers on most rows. What do you do in your first week?",
  "software-engineer":
    "You inherit a Next.js + Supabase app a colleague built with an AI tool in two days. The client goes live Monday. What do you check first, in order, and why?",
};
const SITUATIONAL_FALLBACK =
  "You join a client project where the data is messy and the go-live date is fixed. What do you do in your first week, in order, and why?";

export function situationalQuestion(roleSlug: string): string {
  return SITUATIONAL[roleSlug] ?? SITUATIONAL_FALLBACK;
}

export function salaryBand(min: number, max: number): string {
  return min === max ? rands(min) : `${rands(min)}–${rands(max)}`;
}

export function logisticsQuestion(role: { salary_min: number; salary_max: number; location_note?: string | null }): string {
  const location = role.location_note?.trim();
  return [
    `This role pays ${salaryBand(role.salary_min, role.salary_max)} a month plus year-end profit share.`,
    location ? (/[.!?]$/.test(location) ? location : `${location}.`) : null,
    "What makes this the right next move for you, and when could you start?",
  ]
    .filter(Boolean)
    .join(" ");
}

const STAR_TAIL = "Walk me through what you personally did, which tools you used, and how you measured the result.";

/** Claim text as it reads after "Your CV says you '…'". */
export function quoteClaim(text: string, max = 280): string {
  let t = text.trim().replace(/^["'“”‘’]+|["'“”‘’]+$/g, "").replace(/\s+/g, " ").replace(/[.;,\s]+$/, "");
  // "Built X" → "built X", but keep acronyms/proper starts like "SQL" or "AWS".
  if (/^[A-Z][a-z]/.test(t)) t = t[0].toLowerCase() + t.slice(1);
  if (t.length > max) t = `${t.slice(0, max - 1).trimEnd()}…`;
  return t;
}

export function starQuestion(claim: PlanClaim): string {
  if (claim.kind === "claim") return `Your CV says you '${quoteClaim(claim.text)}'. ${STAR_TAIL}`;
  if (claim.kind === "role") {
    const where = [claim.roleTitle ? `as ${claim.roleTitle}` : null, claim.employer ? `at ${claim.employer}` : null]
      .filter(Boolean)
      .join(" ");
    return `Your CV lists your role ${where}. Pick one piece of work from that role. ${STAR_TAIL}`;
  }
  return `Tell me about ${claim.text}. ${STAR_TAIL}`;
}

/** Stand-ins when a CV has too few claims and roles. */
export const GENERIC_TOPICS = [
  "a recent piece of work you are proud of",
  "a problem you solved using data or software",
  "a time you had to learn a new tool quickly to deliver something",
] as const;

export function introMessage(roleTitle: string): string {
  return [
    `Hi, I'm the Chase Agents screening interviewer for the ${roleTitle} role.`,
    `This is a structured interview with ${TOTAL_QUESTIONS} questions, and I may ask a short follow-up after some answers.`,
    "Please be specific: say what you personally did, and name the tools, numbers and decisions involved.",
    "You have 25 minutes in total. Paste is turned off, so type your answers. Let's start.",
  ].join(" ");
}

export const OFF_SCRIPT_REPLY = "I can't help with that, but let's carry on.";
export const ROLE_QUESTION_REPLY = "Good question, the team will follow up on that.";

export const CLOSING_COMPLETED =
  "Thank you, that was the last question. The interview is complete and your answers have been saved. You'll find your next step on your results page.";
export const CLOSING_TIMEOUT =
  "Time is up, so the interview has ended. Everything you sent before the deadline has been saved. You'll find your next step on your results page.";
